// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ooeoymuaxdznifjjlcfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vZW95bXVheGR6bmlmampsY2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNzY1NDIsImV4cCI6MjA3MTY1MjU0Mn0.3B-y55lO3F3-T5qZUECsiyom2rGTvIHvy4xYdi0BYUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});